#ifndef DESIGNATIONS_H
#define DESIGNATIONS_H

enum Key {UP_LEFT = 0, UP = 1, UP_RIGHT = 2, RIGHT = 3, DOWN_RIGHT = 5,
           DOWN = 6, DOWN_LEFT = 7, LEFT = 8, D_DIG, D_CHANNEL,
           D_UP_STAIR, D_DOWN_STAIR, D_UPDOWN_STAIR,
           D_RAMP, UP_Z, DOWN_Z, SELECT, EOG, EOM, D_CLEAR};

enum DrawMode {M_FREEHAND, M_LINE, M_CURVE, M_RECT, M_ELLIPSE, M_FILL, M_SELECT};

enum BrushType {B_SQUARE, B_CIRCLE};

#endif // DESIGNATIONS_H

